# Generated by Django 5.1.4 on 2024-12-12 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_dynamic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costings', to='tig_costing.department')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(max_length=50)),
                ('old_data', models.TextField()),
                ('new_data', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('costing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='tig_costing.costing')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tig_costing.department')),
                ('expense_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tig_costing.expensehead')),
            ],
        ),
        migrations.AddField(
            model_name='costing',
            name='expense_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tig_costing.expensefield'),
        ),
        migrations.AddField(
            model_name='costing',
            name='expense_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tig_costing.expensehead'),
        ),
    ]
